name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      uses: docker/login-action@v1.14.1
      with:
        registry: registry.cn-hongkong.aliyuncs.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        ecr: auto
        logout: true
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag registry.cn-hongkong.aliyuncs.com/joi/jrecord:latest
    - name: Push Docker image
      run: docker push registry.cn-hongkong.aliyuncs.com/joi/jrecord:latest
